import type { Metadata } from "next";
import Header from "./_components/Header/Header";
import "../sass/main.scss";

export const metadata: Metadata = {
  title: "Blog website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
